name: Build docker image
on:
  workflow_dispatch: {}
  release:
    types: [ published ]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4

      # Sets the latest release tag to env variable ${{ env.LATEST_RELEASE }}
    - name: Get latest release tag
      id: release-label
      run: |
        echo "LATEST_RELEASE=$(git tag --sort=committerdate | tail -1)" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push the Docker
      env:
        IMAGE_TAG: ${{ env.LATEST_RELEASE }}
        IMAGE_NAME: ghcr.io/kollekt-dk/ses-template-manager
      run: |
        docker buildx build . --file Dockerfile --push --platform linux/arm64,linux/amd64 --tag $IMAGE_NAME:$IMAGE_TAG
